require: rubocop-performance

inherit_gem:
  rubocop-shopify: rubocop.yml

AllCops:
  NewCops: enable

Style/FrozenStringLiteralComment:
  Enabled: false
Style/HashSyntax:
  EnforcedShorthandSyntax: never
Style/StringLiterals:
  EnforcedStyle: single_quotes
Style/StringLiteralsInInterpolation:
  EnforcedStyle: single_quotes
Style/SymbolArray:
  EnforcedStyle: percent
Style/WordArray:
  EnforcedStyle: percent
