inherit_gem:
  rubocop-shopify: rubocop.yml

Style/FrozenStringLiteralComment:
  Enabled: false
Style/StringLiterals:
  EnforcedStyle: single_quotes
Style/StringLiteralsInInterpolation:
  EnforcedStyle: single_quotes
Style/SymbolArray:
  EnforcedStyle: percent
Style/WordArray:
  EnforcedStyle: percent
